# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-07 17:25
from django.db import migrations
from django.db import models

import sentinel.models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AlertEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Name")),
                ("endpoint_type", models.TextField(verbose_name="Endpoint Type")),
                ("endpoint_value", models.TextField(verbose_name="Endpoint Value")),
            ],
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="server",
            name="scan_frequency_period",
            field=models.TextField(
                default="minutes", verbose_name="Scan Frequency Period"
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="scan_frequency_value",
            field=models.IntegerField(default=10, verbose_name="Scan Frequency Value"),
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Status Code"
                    ),
                ),
                (
                    "alert_endpoint",
                    models.ForeignKey(
                        on_delete=sentinel.models.AlertEndpoint,
                        to="sentinel.alertendpoint",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=sentinel.models.Server, to="sentinel.server"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alertendpoint",
            name="contact_groups",
            field=models.ManyToManyField(to="sentinel.ContactGroup"),
        ),
    ]
