# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-24 17:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="alertendpoint",
            name="endpoint_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("msteams", "Microsoft Teams"),
                    ("slack", "Slack"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                default="discord",
                max_length=30,
                verbose_name="Endpoint Type",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="scan_frequency_period",
            field=models.CharField(
                choices=[
                    ("minutes", "Minutes"),
                    ("hours", "Hours"),
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                ],
                default="minutes",
                max_length=20,
                verbose_name="Scan Frequency Period",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="scan_frequency_value",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Scan Frequency Value"
            ),
        ),
    ]
