# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-27 12:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0002_auto_20210824_1722")]

    operations = [
        migrations.RenameField(
            model_name="alertendpoint", old_name="endpoint_type", new_name="service"
        ),
        migrations.RenameField(
            model_name="alertendpoint", old_name="endpoint_value", new_name="url"
        ),
    ]
