# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-08 15:23
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0005_alter_serverprofile_server")]

    operations = [
        migrations.RemoveField(model_name="profilechangelog", name="server_profile"),
        migrations.RemoveField(model_name="serverprofile", name="id"),
        migrations.AddField(
            model_name="profilechangelog",
            name="server",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sentinel.server",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="server",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="sentinel.server",
            ),
        ),
    ]
