# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-12 10:20
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0008_alter_serverprofile_latency")]

    operations = [
        migrations.AddField(
            model_name="profilechangelog",
            name="acknowledged",
            field=models.BooleanField(default=False, verbose_name="Acknowledged"),
        ),
        migrations.AlterField(
            model_name="profilechangelog",
            name="date_modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Date Modified",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Date Added",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="date_last_checked",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last Checked"
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(max_length=512, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="server",
            name="scan_frequency_period",
            field=models.CharField(
                choices=[
                    ("Minutes", "Minutes"),
                    ("Hours", "Hours"),
                    ("Days", "Days"),
                    ("Weeks", "Weeks"),
                ],
                max_length=20,
                verbose_name="Scan Frequency Period",
            ),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="dns_records",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="DNS Records"
            ),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="is_up",
            field=models.BooleanField(default=False, verbose_name="Host Reachable"),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="latency",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Latency Results"
            ),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="open_ports",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Open Ports"
            ),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="security_headers",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Security Headers"
            ),
        ),
        migrations.AlterField(
            model_name="serverprofile",
            name="ssl_certs",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="SSL Certificates"
            ),
        ),
    ]
