# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-12 18:29
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("sentinel", "0011_alter_profilechangelog_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servertask",
            name="task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        )
    ]
