# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 09:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0012_alter_servertask_task")]

    operations = [
        migrations.AlterField(
            model_name="alertendpoint",
            name="endpoint_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("msteams", "MS Teams"),
                    ("slack", "Slack"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                max_length=30,
                verbose_name="Endpoint Type",
            ),
        ),
        migrations.AlterField(
            model_name="alertendpoint",
            name="endpoint_value",
            field=models.CharField(max_length=512, verbose_name="Endpoint Value"),
        ),
        migrations.AlterField(
            model_name="alertendpoint",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Name"),
        ),
    ]
