# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 14:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0015_auto_20210813_1514")]

    operations = [
        migrations.AlterField(
            model_name="alertendpoint",
            name="contact_groups",
            field=models.ManyToManyField(
                blank=True, related_name="alertendpoints", to="sentinel.ContactGroup"
            ),
        ),
        migrations.AlterField(
            model_name="profilechangelog",
            name="server",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sentinel.server",
            ),
            preserve_default=False,
        ),
    ]
