# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 15:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0020_alter_server_contact_groups")]

    operations = [
        migrations.RenameField(
            model_name="server", old_name="contact_groups", new_name="contact_group"
        )
    ]
