# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-07-08 18:58
import sentinel.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "domain_name",
                    models.URLField(
                        blank=True, verbose_name="Fully Qualified Domain Name"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "developer",
                    models.CharField(max_length=255, verbose_name="Developer"),
                ),
                ("sysadmin", models.CharField(max_length=255, verbose_name="Sysadmin")),
                ("date_added", models.DateTimeField(verbose_name="Date Added")),
                (
                    "date_last_checked",
                    models.DateTimeField(verbose_name="Last Checked"),
                ),
                (
                    "check_open_ports",
                    models.BooleanField(default=True, verbose_name="Check Open Ports"),
                ),
                (
                    "check_security_headers",
                    models.BooleanField(
                        default=True, verbose_name="Check Security Headers"
                    ),
                ),
                (
                    "check_ssl_certs",
                    models.BooleanField(
                        default=True, verbose_name="Check SSL Certificates"
                    ),
                ),
                (
                    "check_latency",
                    models.BooleanField(default=True, verbose_name="Check Latency"),
                ),
                (
                    "check_dns_records",
                    models.BooleanField(default=True, verbose_name="Check DNS Records"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_up", models.BooleanField(verbose_name="Host Reachable")),
                (
                    "open_ports",
                    models.JSONField(blank=True, null=True, verbose_name="Open Ports"),
                ),
                (
                    "security_headers",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Security Headers"
                    ),
                ),
                (
                    "ssl_certs",
                    models.JSONField(
                        blank=True, null=True, verbose_name="SSL Certificates"
                    ),
                ),
                ("latency", models.IntegerField(verbose_name="Latency")),
                (
                    "dns_records",
                    models.JSONField(blank=True, null=True, verbose_name="DNS Records"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=sentinel.models.Server, to="sentinel.server"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileChangelog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modified", models.DateTimeField(verbose_name="Date Modified")),
                (
                    "changed_field",
                    models.CharField(max_length=255, verbose_name="Changed Field"),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="Old Value"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="New Value"),
                ),
                (
                    "server_profile",
                    models.ForeignKey(
                        on_delete=sentinel.models.ServerProfile,
                        to="sentinel.serverprofile",
                    ),
                ),
            ],
        ),
    ]
