# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-07 19:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0002_auto_20210807_1825")]

    operations = [
        migrations.AlterModelOptions(name="server", options={"verbose_name": "Server"}),
        migrations.AddField(
            model_name="server",
            name="name",
            field=models.TextField(
                default="Default Server Name", unique=True, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
