# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-08 14:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0004_auto_20210808_1316")]

    operations = [
        migrations.AlterField(
            model_name="serverprofile",
            name="server",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sentinel.server"
            ),
        )
    ]
