# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-09 18:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0007_auto_20210808_1723")]

    operations = [
        migrations.AlterField(
            model_name="serverprofile",
            name="latency",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Latency Results"
            ),
        )
    ]
