# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-12 18:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("sentinel", "0009_auto_20210812_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="scan_frequency_period",
            field=models.CharField(
                choices=[
                    ("minutes", "Minutes"),
                    ("hours", "Hours"),
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                ],
                max_length=20,
                verbose_name="Scan Frequency Period",
            ),
        ),
        migrations.CreateModel(
            name="ServerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentinel.server",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
        ),
    ]
