# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-12 18:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0010_auto_20210812_1912")]

    operations = [
        migrations.AlterField(
            model_name="profilechangelog",
            name="server",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sentinel.server",
            ),
        )
    ]
