# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 09:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0013_auto_20210813_1007")]

    operations = [
        migrations.AlterField(
            model_name="alertendpoint",
            name="contact_groups",
            field=models.ManyToManyField(
                blank=True, null=True, to="sentinel.ContactGroup"
            ),
        ),
        migrations.AlterField(
            model_name="alertendpoint",
            name="endpoint_value",
            field=models.CharField(
                max_length=512, verbose_name="Webhook URL/Email Address"
            ),
        ),
    ]
