# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 14:14
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0014_auto_20210813_1045")]

    operations = [
        migrations.AlterModelOptions(
            name="alertendpoint",
            options={
                "verbose_name": "Alert Endpoint",
                "verbose_name_plural": "Alert Endpoints",
            },
        ),
        migrations.AlterModelOptions(
            name="alertlog",
            options={"verbose_name": "Alert Log", "verbose_name_plural": "Alert Logs"},
        ),
        migrations.AlterModelOptions(
            name="contactgroup",
            options={
                "verbose_name": "Contact Group",
                "verbose_name_plural": "Contact Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="profilechangelog",
            options={
                "verbose_name": "Profile Changelog",
                "verbose_name_plural": "Profile Changelogs",
            },
        ),
        migrations.AlterModelOptions(
            name="server",
            options={"verbose_name": "Server", "verbose_name_plural": "Servers"},
        ),
        migrations.AlterModelOptions(
            name="serverprofile",
            options={
                "verbose_name": "Server Profile",
                "verbose_name_plural": "Server Profiles",
            },
        ),
        migrations.AlterField(
            model_name="alertendpoint",
            name="contact_groups",
            field=models.ManyToManyField(blank=True, to="sentinel.ContactGroup"),
        ),
        migrations.AlterField(
            model_name="alertendpoint",
            name="endpoint_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("msteams", "Microsoft Teams"),
                    ("slack", "Slack"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                max_length=30,
                verbose_name="Endpoint Type",
            ),
        ),
        migrations.AlterField(
            model_name="profilechangelog",
            name="server",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sentinel.server",
            ),
        ),
    ]
