# -*- coding: utf-8 -*-
# Generated by Django 3.2.5 on 2021-08-13 14:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("sentinel", "0019_alter_server_contact_groups")]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="contact_groups",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sentinel.contactgroup",
            ),
        )
    ]
