name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install Dependencies
        run: poetry install  --no-interaction
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check
        
      - name: Install Nmap
        run: sudo apt-get install nmap -y

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: theia.settings.CI
        run: poetry run pytest --cov . -n 2
        
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Copy Env File
      env:
        DJANGO_SETTINGS_MODULE: theia.settings.prod
      run: cp .env.example .env

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
